version: "3.7"
services:
  caddy:
    image: serfriz/caddy-cloudflare-ddns:latest  # replace with the desired Caddy build name
    container_name: caddy  # feel free to choose your own container name
    restart: "unless-stopped"  # run container unless stopped by user (optional) 

    # assume the ip address of the host, ports not needed when running on host mode
    network_mode: host  
    # ports:
    #   - "80:80"  # HTTP port
    #   - "443:443"  # HTTPS port
    #   - "443:443/udp"  # HTTP/3 port (optional)

    volumes:
      - caddy-data:/data  # volume mount for certificates data
      - caddy-config:/config  # volume mount for configuration data
      - $PWD/Caddyfile:/etc/caddy/Caddyfile  # to use your own Caddyfile
      - $PWD/log:/var/log  # bind mount for the log directory (optional)
      - $PWD/srv:/srv \  # bind mount to serve static sites or files (optional)

    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}  # Cloudflare API token (if applicable)

volumes:
  caddy-data:
    external: true
  caddy-config:
