services:
  pinchflat:
    container_name: pinchflat
    image: ghcr.io/kieraneglin/pinchflat:latest
    # environment:
    #   # Set the timezone to your local timezone
    #   - TZ=America/New_York
    # ports:
    #   - '8945:8945'
    volumes:
      - ${MUSIC}/new:/downloads/music
      - ${CONFIG}/pinchflat/:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: pinchflat.home.advik.one
      caddy.reverse_proxy: "{{upstreams 8945}}"

  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=002
    volumes:
      - ${SERIES}:/data/series
      - ${MOVIES}:/data/movies
      - ${MUSIC}:/data/music
      - ${CONFIG}/jellyfin/:/config
      # - ${CACHE}/jellyfin/:/transcode
      - /etc/localtime:/etc/localtime:ro
    # Hardware Acceleration
    # devices == video card
    # render/video group is needed to access the video card; getent group render
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "989"
    # ports:
    #   - 8096:8096
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: jellyfin.home.advik.one
      caddy.reverse_proxy: "{{upstreams 8096}}"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    restart: unless-stopped

  green-tunnel:
    image: sadeghhayeri/green-tunnel
    container_name: green-tunnel
    # environment:
    #   - DNS_SERVER=""
    # ports:
    #   - 8000:8000
    networks:
      - internal
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/prowlarr:/config
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 9696:9696
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: prowlarr.home.advik.one
      caddy.reverse_proxy: "{{upstreams 9696}}"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/radarr:/config
      - ${MOVIES}:/movies
      - ${DOWNLOADS}:/downloads
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 7878:7878
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: radarr.home.advik.one
      caddy.reverse_proxy: "{{upstreams 7878}}"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${SERIES}:/series
      - ${DOWNLOADS}:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: sonarr.home.advik.one
      caddy.reverse_proxy: "{{upstreams 8989}}"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/bazarr:/config
      - ${MOVIES}:/movies
      - ${SERIES}:/series
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 6767:6767
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: bazarr.home.advik.one
      caddy.reverse_proxy: "{{upstreams 6767}}"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - WEBUI_PORT=10000
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG}/qbittorrent:/config/qBittorrent
      - ${DOWNLOADS}:/downloads
    ports:
      # - 10000:10000
      - 6881:6881
      - 6881:6881/udp
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: qbittorrent.home.advik.one
      caddy.reverse_proxy: "{{upstreams 10000}}"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
    volumes:
      - ${CONFIG}/jellyseerr:/app/config
    # ports:
    #   - 5055:5055
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: jellyseerr.home.advik.one
      caddy.reverse_proxy: "{{upstreams 5055}}"

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg
    volumes:
      - ${CONFIG}/lazylibrarian:/config
      - ${DOWNLOADS}:/downloads
      - ${BOOKS}:/books
      - ${AUDIOBOOKS}:/audiobooks
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 5299:5299
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: lazylibrarian.home.advik.one
      caddy.reverse_proxy: "{{upstreams 5299}}"

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${CONFIG}/kavita/:/config
      - ${DATA}:/data
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 5000:5000
    networks:
      - internal
    restart: unless-stopped
    labels:
      caddy: kavita.home.advik.one
      caddy.reverse_proxy: "{{upstreams 5000}}"

networks:
  internal:
    external: true
