---
id: heavens-hell
name: Heavens-Hell
description: "Heavens-Hell is a Private Torrent Tracker for MUSIC / AUDIO SOFTWARE"
language: en-US
type: private
encoding: UTF-8
links:
  - https://heavens-hell.info/

caps:
  categorymappings:
    - {id: 39, cat: Audio, desc: "Albums"}
    - {id: 40, cat: Audio, desc: "Alternative"}
    - {id: 4, cat: PC, desc: "Apps"}
    - {id: 50, cat: PC, desc: "Apps -- Miscellaneous"}
    - {id: 11, cat: Audio, desc: "Billboard Top 100"}
    - {id: 7, cat: Audio, desc: "Blues"}
    - {id: 8, cat: Audio, desc: "Chillout"}
    - {id: 41, cat: Audio, desc: "Christmas"}
    - {id: 9, cat: Audio, desc: "Classical"}
    - {id: 12, cat: Audio, desc: "Country"}
    - {id: 10, cat: Audio, desc: "Dance"}
    - {id: 13, cat: Audio, desc: "Discography"}
    - {id: 42, cat: Audio, desc: "DJ Music"}
    - {id: 44, cat: Audio, desc: "DJ Music -- Funkymix"}
    - {id: 45, cat: Audio, desc: "DJ Music -- Promo Only"}
    - {id: 43, cat: Audio, desc: "DJ Music -- Ultimix"}
    - {id: 21, cat: Audio, desc: "DJ Radio Sets"}
    - {id: 19, cat: Audio, desc: "DMC"}
    - {id: 20, cat: Audio, desc: "Drum&Bass"}
    - {id: 22, cat: Audio/Lossless, desc: "Flac Music"}
    - {id: 23, cat: Audio/Lossless, desc: "Flac-24 Bit Hi-Res"}
    - {id: 14, cat: Audio, desc: "Funk"}
    - {id: 15, cat: Audio, desc: "Hardcore"}
    - {id: 16, cat: Audio, desc: "Hip hop"}
    - {id: 24, cat: Audio, desc: "House"}
    - {id: 17, cat: Audio, desc: "Jazz"}
    - {id: 25, cat: Audio, desc: "Jungle"}
    - {id: 46, cat: Audio, desc: "K3 WAV"}
    - {id: 49, cat: Audio/Other, desc: "K3 WAV -- Other WAV"}
    - {id: 18, cat: Audio, desc: "Karaoke"}
    - {id: 26, cat: Audio, desc: "Mastermix"}
    - {id: 28, cat: Audio, desc: "Metal"}
    - {id: 27, cat: Audio/MP3, desc: "MP3 NEW RELEASES"}
    - {id: 51, cat: Audio/MP3, desc: "MP3 -- Other MP3"}
    - {id: 33, cat: Audio, desc: "Music Packs"}
    - {id: 32, cat: Audio/Video, desc: "Music Videos"}
    - {id: 29, cat: Audio, desc: "Oldies"}
    - {id: 47, cat: Audio, desc: "Pop music"}
    - {id: 30, cat: Audio, desc: "Punk"}
    - {id: 34, cat: Audio, desc: "R&B/Motown"}
    - {id: 35, cat: Audio, desc: "Reggae"}
    - {id: 36, cat: Audio, desc: "Retro"}
    - {id: 31, cat: Audio, desc: "Rock"}
    - {id: 37, cat: Audio, desc: "Soul"}
    - {id: 48, cat: Audio, desc: "Trance"}
    - {id: 38, cat: Audio, desc: "VIPs only"}

  modes:
    search: [q]
    music-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: freeleech
    type: checkbox
    label: Filter freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: added
    options:
      added: created
      seeders: seeders
      size: size
      name: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc
  - name: info_tpp
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrents per page:</b> setting to <b>40</b> on your account profile. The Default is <i>15</i>.
  - name: flaresolverr
    type: info
    label: FlareSolverr
    default: This site may use Cloudflare DDoS Protection, therefore Prowlarr requires <a href="https://wiki.servarr.com/prowlarr/faq#can-i-use-flaresolverr-indexers" target="_blank" rel="noreferrer">FlareSolverr</a> to access it.
  - name: info_activity
    type: info
    label: Account Inactivity
    default: "To keep records updated regularly, all inactive accounts will be deleted after 60 days of inactivity."

login:
  path: takelogin.php
  method: post
  inputs:
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    logout: ""
  error:
    - selector: table:has(a[href*="login.php?error=1"])
      message:
        text: "ERROR: Incorrect username!"
    - selector: table:has(a[href*="login.php?error=4"])
      message:
        text: "ERROR: Incorrect password!"
    - selector: table:has(a[href*="login.php?error="])
      message:
        text: "ERROR: Something went wrong during login!"
  test:
    path: index.php
    selector: a[href*="/logout.php?logouthash="]

download:
  before:
    path: takethanks.php
    method: post
    inputs:
      torrentid: "{{ .DownloadUri.Query.id }}"
  selectors:
    - selector: a[href*="download.php?id="]
      attribute: href

search:
  paths:
    - path: browse.php
      method: post
  keywordsfilters:
    - name: re_replace
      args: ["[\\s]+", "%"]
  inputs:
    do: search
    keywords: "{{ .Keywords }}"
    # t_name, t_description, t_both, t_uploader, t_genre
    search_type: t_name
    # does not support multi category searching so defaulting to all.
    category: 0
    # yes, no
    include_dead_torrents: yes
    sort: "{{ if .Config.freeleech }}free{{ else }}{{ .Config.sort }}{{ end }}"
    order: "{{ if .Config.freeleech }}asc{{ else }}{{ .Config.type }}{{ end }}"

  rows:
    selector: "table.sortable tr:has(a[href*=\"/download.php?id=\"]){{ if .Config.freeleech }}:has(img[src$=\"/freedownload.gif\"]){{ else }}{{ end }}"

  fields:
    category:
      selector: a[href*="/browse.php?category="]
      attribute: href
      filters:
        - name: querystring
          args: category
    title_default:
      # is usually abbreaviated
      selector: a[href*="/details.php?id="]
    title:
      # while still abbreviated, is usually longer than the default
      selector: div.tooltip-content div
      optional: true
      default: "{{ .Result.title_default }}"
    details:
      selector: a[href*="/details.php?id="]
      attribute: href
    download:
      selector: a[href*="/details.php?id="]
      attribute: href
    poster:
      selector: img[src*="/torrents/images/"]
      attribute: src
    date:
      selector: td:nth-child(2)
      # auto adjusted by site account profile
      filters:
        - name: regexp
          args: "(\\d{2}-\\d{2}-\\d{4} \\d{2}:\\d{2})"
        - name: dateparse
          args: "dd-MM-yyyy HH:mm"
    size:
      selector: td:nth-last-child(5)
    grabs:
      selector: td:nth-last-child(4)
    seeders:
      selector: td:nth-last-child(3)
    leechers:
      selector: td:nth-last-child(2)
    description:
      # Wait: 4 h
      selector: div.tooltip-content > div:last-child
    downloadvolumefactor:
      case:
        img[src$="/freedownload.gif"]: 0
        img[src$="/silverdownload.gif"]: 0.5
        "*": 1
    uploadvolumefactor:
      case:
        img[src$="/x2.gif"]: 2
        "*": 1
    minimumratio:
      text: 0.5
    minimumseedtime:
      # 1 day (as seconds = 24 x 60 x 60)
      text: 86400
# TS Special Edition v.8.0
